import path from "node:path";
import { expandTilde } from "./config-generator.js";
import type { GeneratedScript, UserConfig } from "./types.js";

function generateU2mScript(profileName: string): string {
  return `#!/usr/bin/env node
// gen_otel_headers_u2m.js - U2M OAuth token helper for Claude Code OTEL
// Generated by setup-zerobus-otel

const { execSync } = require("child_process");

const profile = ${JSON.stringify(profileName)};

function getToken() {
  return execSync("databricks auth token --profile " + profile, { timeout: 10000 });
}

let result;
try {
  result = getToken();
} catch (e) {
  process.stderr.write("Token expired. Running 'databricks auth login --profile " + profile + "' ...\\n");
  try {
    execSync("databricks auth login --profile " + profile, { stdio: "inherit", timeout: 10000 });
  } catch (e2) {
    process.stderr.write("ERROR: 'databricks auth login' failed.\\n");
    process.exit(1);
  }
  try {
    result = getToken();
  } catch (e3) {
    process.stderr.write("ERROR: Failed to get token after login. Run 'databricks auth login --profile " + profile + "' manually.\\n");
    process.exit(1);
  }
}

const token = JSON.parse(result.toString()).access_token;
if (!token) {
  process.stderr.write("ERROR: No access_token in response.\\n");
  process.exit(1);
}

console.log(JSON.stringify({ Authorization: "Bearer " + token }));
`;
}

function generateM2mScript(): string {
  return `#!/usr/bin/env node
// gen_otel_headers_m2m.js - M2M (Service Principal) OAuth token helper for Claude Code OTEL
// Generated by setup-zerobus-otel

const { execSync } = require("child_process");

const host = process.env.DATABRICKS_HOST;
const clientId = process.env.DATABRICKS_CLIENT_ID;
const clientSecret = process.env.DATABRICKS_CLIENT_SECRET;

if (!clientId || !clientSecret) {
  process.stderr.write("ERROR: DATABRICKS_CLIENT_ID and DATABRICKS_CLIENT_SECRET must be set.\\n");
  process.exit(1);
}
if (!host) {
  process.stderr.write("ERROR: DATABRICKS_HOST must be set.\\n");
  process.exit(1);
}

let result;
try {
  result = execSync(
    "curl -sfS -X POST " + host + "/oidc/v1/token"
    + " -H \\"Content-Type: application/x-www-form-urlencoded\\""
    + " -d \\"grant_type=client_credentials&scope=all-apis\\""
    + " -u " + clientId + ":" + clientSecret,
    { timeout: 30000 }
  );
} catch (e) {
  process.stderr.write("ERROR: Failed to get token from " + host + "/oidc/v1/token\\n");
  process.exit(1);
}

const token = JSON.parse(result.toString()).access_token;
if (!token) {
  process.stderr.write("ERROR: No access_token in response.\\n");
  process.exit(1);
}

console.log(JSON.stringify({ Authorization: "Bearer " + token }));
`;
}

export function generateTokenScript(
  config: UserConfig,
): GeneratedScript | null {
  if (config.authMethod === "pat") {
    return null;
  }

  const fileName =
    config.authMethod === "u2m"
      ? "gen_otel_headers_u2m.js"
      : "gen_otel_headers_m2m.js";

  const filePath = path.join(expandTilde(config.scriptLocation), fileName);
  const content =
    config.authMethod === "u2m"
      ? generateU2mScript(config.profileName!)
      : generateM2mScript();

  return { filePath, content, fileName };
}
